Add metrics for disabling Pocket in New Tab.
mozilla/mozanalysis pull request #122
Opened 2021-01-25 23:27 UTC by kirill-demtchouk

The telemetry to properly calculate the number of users un-ticking the options to show Pocket and/or Pocket sponsored stories in New Tab was added to FX86 🎉

2021-01-26 16:47 UTC, tdsmith requested changes
duplicating the feedback from CI

2021-01-26 16:47 UTC, tdsmith commented on src/mozanalysis/metrics/desktop.py
> +pocket_rec_clicks = Metric(
```suggestion
disable_pocket_clicks = Metric(
```

2021-01-26 16:47 UTC, tdsmith commented on src/mozanalysis/metrics/desktop.py
> +    """
```suggestion
        """\
         Counts the number of clicks to disable Pocket sponsored content
         in New Tab made by each client.
    """
```

2021-01-26 17:28 UTC, kirill-demtchouk commented
Whoops, good catch. I PR-ed too fast. These should be fixed now!

2021-01-28 22:29 UTC, tdsmith commented on src/mozanalysis/metrics/desktop.py
> +                AND JSON_EXTRACT_SCALAR(value, '$.status') = false
This is inconsistent with line 355 above; should this be `false` or `'false'` here?

2021-01-28 22:30 UTC, tdsmith approved these changes
lgtm except for the data type question

2021-01-28 23:23 UTC, merged